# Generated by Django 4.2.3 on 2023-09-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_order_stripe_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
