# Generated by Django 4.2.3 on 2023-09-07 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_order_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="slug",
            new_name="shopping_id",
        ),
    ]
