# Generated by Django 4.2.3 on 2023-09-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_rename_slug_order_shopping_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shopping_id",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
