# Generated by Django 4.2.3 on 2023-09-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_order_shopping_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_paid",
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "پرداخت نشده"),
                    ("in_proccesing", "در حال پردازش انبار"),
                    ("sended", "خروج از انبار"),
                ],
                default="not_paid",
                max_length=20,
            ),
        ),
    ]
