# Generated by Django 4.2.3 on 2023-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0007_alter_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "پرداخت نشده"),
                    ("in_proccesing", "در حال پردازش انبار"),
                    ("sended", "خروج از انبار"),
                    ("delivered", "تحویل داده شد"),
                    ("cancelled", "لغو شده"),
                ],
                default="not_paid",
                max_length=20,
            ),
        ),
    ]
