# Generated by Django 4.2.3 on 2023-08-30 13:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("home", "0005_templatesettings_order_deliver_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام دسته بندی"),
                ),
                (
                    "return_condition",
                    models.TextField(
                        default="برای کالاهای گروه موبایل، امکان برگشت کالا به دلیل انصراف از خرید تنها در صورتی مورد قبول است که کالا بدون هیچگونه استفاده و با تمامی قطعات، متعلقات و بسته\u200cبندی\u200cهای اولیه خود بازگردانده شود. لازم به ذکر است که برای هر کالای موبایل، ضمانت رجیستری صادر می\u200cشود. در صورت بروز اشکال در ضمانت رجیستری، پس از انقضای مدت ۳۰ روزه، کالا می\u200cتواند بازگردانده شود."
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="", verbose_name="عکس دسته بندی"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
                ("is_special", models.BooleanField(default=False)),
                ("brand", models.ManyToManyField(to="home.brands")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=450, verbose_name="نام محصول")),
                ("image", models.ImageField(upload_to="", verbose_name="عکس محصول")),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
                ("count", models.PositiveIntegerField()),
                ("price", models.PositiveIntegerField()),
                (
                    "discount_percentage",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                ("specification", models.TextField()),
                ("description", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_show", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="home.brands"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhotoGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="عکس محصول")),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
                ("text", models.CharField(max_length=150)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("text", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_show",
                    models.BooleanField(default=False, verbose_name="نمایش داده شود؟"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.profile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CategoryDepthTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام زیر دسته بندی"),
                ),
                (
                    "link",
                    models.CharField(max_length=100, verbose_name="لینک زیر دسته بندی"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.category",
                    ),
                ),
            ],
        ),
    ]
