# Generated by Django 4.2.3 on 2023-08-30 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="discount_percentage",
            new_name="discount",
        ),
        migrations.RemoveField(
            model_name="photogallery",
            name="alt",
        ),
        migrations.AddField(
            model_name="comment",
            name="score",
            field=models.PositiveSmallIntegerField(
                null=True,
                validators=[django.core.validators.MaxValueValidator(10)],
                verbose_name="امتیاز محصول",
            ),
        ),
    ]
