# Generated by Django 4.2.3 on 2023-08-31 13:38

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_rename_discount_percentage_product_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=[("#FFFFFF", "white"), ("#000000", "black")],
            ),
        ),
    ]
