# Generated by Django 4.2.3 on 2023-09-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_product_sales_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_special",
            field=models.BooleanField(default=False),
        ),
    ]
