# Generated by Django 4.2.3 on 2023-12-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_product_is_special"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.JSONField()),
            ],
        ),
    ]
