# Generated by Django 4.2.3 on 2023-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_testmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specification",
            field=models.JSONField(null=True),
        ),
    ]
