# Generated by Django 4.2.3 on 2023-12-17 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_alter_product_specification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
