# Generated by Django 4.2.3 on 2023-12-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_delete_testmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="important_specification",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CategoryDepthTwo",
        ),
    ]
