# Generated by Django 4.2.3 on 2023-12-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0011_category_important_specification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="important_specification",
            field=models.TextField(),
        ),
    ]
