# Generated by Django 4.2.3 on 2023-08-30 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="عکس برند")),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="NavBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام نوبار")),
                ("link", models.CharField(max_length=100, verbose_name="لینک نوبار")),
                ("icon", models.CharField(max_length=50, verbose_name="ایکون")),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="", verbose_name="عکس سلایدر")),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
                ("link", models.CharField(max_length=100, verbose_name="ادرس دکمه")),
            ],
        ),
        migrations.CreateModel(
            name="TemplateSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("top_navbar", models.ImageField(upload_to="")),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(upload_to="", verbose_name="بنر میانی راست"),
                ),
                ("banner1", models.ImageField(upload_to="")),
                (
                    "alt1",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
                (
                    "banner2",
                    models.ImageField(upload_to="", verbose_name="بنر میانی چپ"),
                ),
                (
                    "alt2",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
                (
                    "banner3",
                    models.ImageField(upload_to="", verbose_name="بنر میانی پایین"),
                ),
                (
                    "alt3",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnderSlider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "image",
                    models.ImageField(upload_to="", verbose_name="عکس زیر اسلایدر"),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        default="image",
                        max_length=100,
                        null=True,
                        verbose_name="توضیح عکس",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NavBarDepthTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام نوبار")),
                ("link", models.CharField(max_length=100, verbose_name="لینک نوبار")),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="home.navbar"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FooterDepthTwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "link",
                    models.CharField(
                        max_length=100, null=True, verbose_name="لینک صفحه"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="home.footer"
                    ),
                ),
            ],
        ),
    ]
