# Generated by Django 4.2.3 on 2023-08-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_footerdepthtwo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatesettings",
            name="alt_logo",
            field=models.CharField(
                blank=True,
                default="image",
                max_length=100,
                null=True,
                verbose_name="توضیح عکس",
            ),
        ),
        migrations.AlterField(
            model_name="templatesettings",
            name="banner1",
            field=models.ImageField(upload_to="", verbose_name="بنر میانی راست"),
        ),
        migrations.AlterField(
            model_name="templatesettings",
            name="logo",
            field=models.ImageField(upload_to="", verbose_name="لوگو"),
        ),
    ]
