# Generated by Django 4.2.3 on 2023-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_templatesettings_alt_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatesettings",
            name="copyright_text",
            field=models.CharField(default="all rights reserved", max_length=150),
        ),
        migrations.AlterField(
            model_name="templatesettings",
            name="top_navbar",
            field=models.ImageField(upload_to="", verbose_name="بنر بالا"),
        ),
    ]
