# Generated by Django 4.2.3 on 2023-08-30 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("home", "0005_templatesettings_order_deliver_time"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Brands",
            new_name="Brand",
        ),
    ]
