# Generated by Django 4.2.3 on 2023-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_rename_brands_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
