# Generated by Django 4.2.3 on 2023-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_brand_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
