# Generated by Django 4.2.3 on 2023-09-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_brand_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactUsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="ادرس فروشگاه")),
                (
                    "email",
                    models.TextField(
                        blank=True, null=True, verbose_name="ایمیل فروشگاه"
                    ),
                ),
                ("phone_number", models.TextField(verbose_name="شماره تلفن فروشگاه")),
            ],
        ),
        migrations.CreateModel(
            name="ContectUsKeeprt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=155)),
                ("last_name", models.CharField(max_length=155)),
                ("phone_number", models.CharField(max_length=20)),
                ("text", models.TextField()),
                ("is_email_answer", models.BooleanField(default=True)),
            ],
        ),
    ]
