# Generated by Django 4.2.3 on 2023-09-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="description",
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="zip_code",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
