# Generated by Django 4.2.3 on 2023-09-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_profile_national_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="send_add_email",
            field=models.BooleanField(default=True),
        ),
    ]
