# Generated by Django 4.2.3 on 2023-09-05 10:32

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_profile_send_add_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                max_length=20, null=True, validators=[cart.models.validate_phone_number]
            ),
        ),
    ]
