# Generated by Django 4.2.3 on 2023-09-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_profilemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verify_code",
            field=models.CharField(default="test", max_length=10),
        ),
    ]
