# Generated by Django 4.2.3 on 2023-09-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_user_verify_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verify_code",
            field=models.CharField(max_length=10),
        ),
    ]
