# Generated by Django 4.2.3 on 2023-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_profile_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileSideBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="اسم لینک")),
                ("link", models.CharField(max_length=20, verbose_name="لینک")),
            ],
        ),
    ]
