# Generated by Django 4.2.3 on 2023-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0010_userprofilesidebar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilesidebar",
            name="link",
            field=models.CharField(max_length=100, verbose_name="لینک"),
        ),
        migrations.AlterField(
            model_name="userprofilesidebar",
            name="name",
            field=models.CharField(max_length=30, verbose_name="اسم لینک"),
        ),
    ]
