# Generated by Django 4.2.3 on 2023-09-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_alter_userprofilesidebar_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilesidebar",
            name="icon",
            field=models.CharField(max_length=30, null=True, verbose_name="ایکون لینک"),
        ),
    ]
